### ISSUE TITLE
Support for SDK 29

### ISSUE THREAD

**Issue by TheDoorNextBoy** [freshdesk/freshchat-android#59] opened 2019-10-29 09:38 UTC
Hi,
at the moment the FAQ crashes when I update to Android SDK 29 and start it (on an Android Q device or emulator).
Could you have a look at that?
Let me know if you need more information, but I think this should be easy to reproduce.
Thank you

**Comment by rameshfreshworks** [comment] 2019-10-30 12:24
Hi @TheDoorNextBoy   
We could not reproduce this at our end. Please contact our support by emailing to support@freshchat.com, We will let you know how to take this forward.

**Comment by TheDoorNextBoy** [comment] 2019-11-01 10:19
Hi @rameshfreshworks 
I found the problem. It crashes when setting a custom font with Calligraphy as described here https://support.freshchat.com/support/solutions/articles/229492-freshchat-android-sdk-themes-and-customizations and when targeting SDK 29 and running on a device with 29.
I will try to fix that. Maybe updating Calligraphy to 3.x (2.x is no longer continued) fixes it. I'll let you know.

**Comment by TheDoorNextBoy** [comment] 2019-11-01 11:14
So I removed Calligraphy and everything is working fine now.
The recommended way should be to use the `<item name="android:fontFamily">@font/my_custom_font</item>` style attribute. Maybe you can update your documentation.
Feel free to close the ticket.
Cheers

**Comment by rameshfreshworks** [comment] 2019-11-01 11:41
Thanks for the update @TheDoorNextBoy. I am closing this issue now.

**Closed by rameshfreshworks** 2019-11-01 11:41 UTC
