### ISSUE TITLE
Infinite loading in FreshChat after fresh installation

### ISSUE THREAD

**Issue by kabirkhaan** [freshdesk/freshchat-android#79] opened 2020-02-19 12:03 UTC
## Steps to reproduce:
- Fresh install the app (or clear storage)
 - Click FreshChat button

The issue will reproduce when right after initializing the chat user open chat, while user properties and channel are syncing.
 After closing the chat and open it again it will fix the issue

### Actual
- Loading is not disappearing,
### Expected
- After syncing, loading should finish and user should see the chat

**Comment by Duraivel-Perumal** [comment] 2020-02-19 12:50
Hi, Kabir Khan can you share your freshchat sdk version?

**Comment by kabirkhaan** [comment] 2020-02-19 14:01
> Hi Kabir Khan, can you share your freshchat sdk version?

version -> "3.0.0"

**Comment by vitorreis** [comment] 2020-02-26 09:27
+1 do we have an update here  @Duraivel-Perumal

**Comment by Duraivel-Perumal** [comment] 2020-02-26 09:34
> > Hi Kabir Khan, can you share your freshchat sdk version?
> 
> version -> "3.0.0"

Hi Please update the SDK version to latest

**Comment by Duraivel-Perumal** [comment] 2020-02-26 09:41
@kabirkhaan @vitorreis 
We are unable to reproduce this at our end. Can you try reproducing this issue in our sample app and share the code?

Sample code: https://github.com/freshdesk/freshchat-android/tree/master/Sample/FreshchatSample

**Comment by kariot** [comment] 2020-04-29 13:18
I'm also facing the same issue, can't see the chat screen.
Version I'm using: `3.3.0`
Also, I have,
1. Checked Init method is called before starting the conversation
2. Checked the App ID & App Key

**Comment by mageshr24** [comment] 2020-05-01 16:29
> I'm also facing the same issue, can't see the chat screen.
> Version I'm using: `3.3.0`
> Also, I have,
> 
> 1. Checked Init method is called before starting the conversation
> 2. Checked the App ID & App Key
>    But I have an another set of App Id & App Key from my an app, which works absolutely fine. The issue occurs only when I change the ID & Key from the new account


I'm also facing the exact issue right now, Did you figure out the problem??

**Comment by kariot** [comment] 2020-05-01 19:38
> > I'm also facing the same issue, can't see the chat screen.
> > Version I'm using: `3.3.0`
> > Also, I have,
> > 
> > 1. Checked Init method is called before starting the conversation
> > 2. Checked the App ID & App Key
> >    But I have an another set of App Id & App Key from my an app, which works absolutely fine. The issue occurs only when I change the ID & Key from the new account
> 
> I'm also facing the exact issue right now, Did you figure out the problem??

Not yet, I just contacted them by email two days back but there were no response

**Comment by rameshfreshworks** [comment] 2020-05-02 03:51
Hi @kariot  and @mageshr24 ,

The issue could be due to one of the following primary reasons
1. App id and App key was incorrectly set 
2. Need to set the designated domain based on the Datacenter using FreshchatConfig.setDomain() 

Default - msdk.freshchat.com ( Pointed to this without setup)
EU - msdk.eu.freshchat.com
India - msdk.in.freshchat.com
Australia - msdk.au.freshchat.com

Let us know if this helps?

**Comment by kariot** [comment] 2020-05-02 05:41
Issue was solved when domain changed to one in India, Thank You

> Hi @kariot and @mageshr24 ,
> 
> The issue could be due to one of the following primary reasons
> 
> 1. App id and App key was incorrectly set
> 2. Need to set the designated domain based on the Datacenter using FreshchatConfig.setDomain()
> 
> Default - msdk.freshchat.com ( Pointed to this without setup)
> EU - msdk.eu.freshchat.com
> India - msdk.in.freshchat.com
> Australia - msdk.au.freshchat.com
> 
> Let us know if this helps?

Issue was solved when the domain changed to india. Thank You

**Comment by mageshr24** [comment] 2020-05-02 06:46
> Hi @kariot and @mageshr24 ,
> 
> The issue could be due to one of the following primary reasons
> 
> 1. App id and App key was incorrectly set
> 2. Need to set the designated domain based on the Datacenter using FreshchatConfig.setDomain()
> 
> Default - msdk.freshchat.com ( Pointed to this without setup)
> EU - msdk.eu.freshchat.com
> India - msdk.in.freshchat.com
> Australia - msdk.au.freshchat.com
> 
> Let us know if this helps?

The issue was solved. Thank you sir

**Closed** 2020-08-07 12:49 UTC
