### ISSUE TITLE
ChannelListActivity: Error inflating class androidx.appcompat.widget.ActionBarOverlayLayout

### ISSUE THREAD

**Issue by mariantonia** [freshdesk/freshchat-android#86] opened 2020-05-18 13:35 UTC
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx/com.freshchat.consumer.sdk.activity.ChannelListActivity}: android.view.InflateException: Binary XML file line #17 in com.xxxxx:layout/abc_screen_toolbar: Binary XML file line #17 in com.xxxx:layout/abc_screen_toolbar: Error inflating class androidx.appcompat.widget.ActionBarOverlayLayout
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3488)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3635)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2175)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7860)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
     Caused by: android.view.InflateException: Binary XML file line #17 in com.xxx:layout/abc_screen_toolbar: Binary XML file line #17 in com.xxx:layout/abc_screen_toolbar: Error inflating class androidx.appcompat.widget.ActionBarOverlayLayout
     Caused by: android.view.InflateException: Binary XML file line #17 in com.xxxx:layout/abc_screen_toolbar: Error inflating class androidx.appcompat.widget.ActionBarOverlayLayout
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.reflect.Field.get(java.lang.Object)' on a null object reference
        at uk.co.chrisjenx.calligraphy.ReflectionUtils.getValue(ReflectionUtils.java:29)
        at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:203)
        at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20)
        at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater$PrivateWrapperFactory2.onCreateView(CalligraphyLayoutInflater.java:302)
        at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:239)
        at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1069)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:997)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:659)
        at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.inflate(CalligraphyLayoutInflater.java:60)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)

**Comment by rameshfreshworks** [comment] 2020-05-19 05:19
Hi @mariantonia ,  Do you use custom fonts by using calligraphy library in your app? The older calligraphy library seems to be incompatible with the latest OS version due to restrictions and deemed as end-of-life.

**Comment by rameshfreshworks** [comment] 2020-08-07 12:46
Closing this issue. Feel free to reopen if the issue is not resolved.

**Closed by rameshfreshworks** 2020-08-07 12:46 UTC

**Comment by rituapplocum** [comment] 2020-10-26 09:26
What is the solution for the above issue?
