### ISSUE TITLE
Fatal Exception: android.app.RemoteServiceException

### ISSUE THREAD

**Issue by j2emanue** [freshdesk/freshchat-android#34] opened 2018-11-14 10:15 UTC
Bad notification posted from package com.mobile.mycompany: Couldn't expand RemoteViews for: StatusBarNotification(pkg=com.mobile.mycompany user=UserHandle{0} id=-674111321 tag=null key=0|com.mobile.mycompany|-674111321|null|10247: Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x18 color=0x00000000 vis=PUBLIC semFlags=0x0 semPriority=0))

can you guys take a look at this. its for android 7 devices only.  OneSignal had this issue also:

for reference: 
https://github.com/OneSignal/OneSignal-Android-SDK/issues/263#issuecomment-348664720

i want you guys to tell me how to stop the crash which seems to occur on an update of the app. 

Info:
com.github.freshdesk:freshchat-android:1.3.1@aar

  100% samsung users are affected by this issue. 96% of the users were in the background when it occured. one particular device is
   SM-G610F. all the crashes occurred on android 7 which is api 24.

stacktrace:

IntentService[FreshchatService]
       at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(NativeCrypto.java)
       at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:364)
       at com.android.okhttp.Connection.connectTls(Connection.java:1510)
       at com.android.okhttp.Connection.connectSocket(Connection.java:1458)
       at com.android.okhttp.Connection.connect(Connection.java:1413)
       at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:1700)
       at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:133)
       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:466)
       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:371)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:503)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:130)
       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java)
       at com.freshchat.consumer.sdk.e.c.a(Unknown Source)
       at com.freshchat.consumer.sdk.e.c.e(Unknown Source)
       at com.freshchat.consumer.sdk.e.c.af(Unknown Source)
       at com.freshchat.consumer.sdk.e.a.cX(Unknown Source)
       at com.freshchat.consumer.sdk.service.c.s.b(Unknown Source)
       at com.freshchat.consumer.sdk.service.c.s.b(Unknown Source)
       at com.freshchat.consumer.sdk.service.b.b.b(Unknown Source)
       at com.freshchat.consumer.sdk.service.FreshchatService.onHandleIntent(Unknown Source)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:67)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by tryprasannan** [comment] 2018-11-15 12:51
@j2emanue Thanks for reporting this. Freshchat SDK doesn't restore notifications, it may just be open notifications during app update causing the issue. We'll investigate this further and share an update when we have more information.

**Comment by MuthuFD** [comment] 2019-07-17 07:15
Hi @j2emanue , We are unable to reproduce this. 

Please feel free to try out our latest version of SDK and reopen if this issue is still present.

Closing this issue now.

**Closed by MuthuFD** 2019-07-17 07:15 UTC
